# Generated by Django 3.2.8 on 2021-10-17 17:30

from django.db import migrations
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=products.models.LowerCaseCharField(max_length=30, unique=True, verbose_name='Name'),
        ),
    ]
